name: boatinstrument
description: "A configurable Boat Instrument."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.9.1+10

environment:
  sdk: '>=3.8.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  path_provider:
  http:
  json_annotation:
  format:
  slide_to_act:
  web_socket_channel:
  vector_math:
  logger:
  circular_buffer:
  resizable_widget:
  latlong_formatter:
  wakelock_plus:
  nanoid:
  share_plus:
  file_picker:
  filesystem_picker:
  provider:
  flutter_inappwebview:
  screen_brightness:
  flutter_email_sender:
  intl:
  # We can't use the pure dart implementation "multicast_dns" because Apple doesn't allow
  # you to create multicast ports.
  # See: https://github.com/flutter/flutter/issues/42102#issuecomment-2308904083
  bonsoir:
  audioplayers:
  latlong2:
  args:
  markdown_widget:
  url_launcher: 
  flutter_rfb:
  flutter_material_color_picker:
  color_hex:
  flutter_fullscreen:
  text_scroll:
  flutter_onscreen_keyboard:
  collection:
#  great_circle_distance_calculator:
  actions_menu_appbar:
    path: ../actions_menu_appbar

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

  build_runner:
  json_serializable:
  msix: ^3.16.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/
    - assets/doc/
    - assets/icons/
    - assets/icons/dark/
    - assets/icons/light/
    - assets/starlink/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Red Hat Mono
      fonts:
        - asset: fonts/RedHatMono-Regular.ttf
    - family: Awesome
      fonts:
        - asset: fonts/Font-Awesome-7-Free-Solid-900.otf

msix_config:
  display_name: Boat Instrument
  publisher_display_name: Phil Seeley
  identity_name: PhilSeeley.BoatInstrument
  publisher: CN=4F8DE92B-051C-4FBD-9588-EF56D61221E6
  logo_path: assets\icon.png
